# Generated by Django 4.2.16 on 2024-10-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User/Patient'), ('doctor', 'Doctor')], default='user', max_length=10),
        ),
    ]
