# Generated by Django 4.2.16 on 2024-11-22 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Product Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price (USD)')),
                ('short_description', models.CharField(max_length=500, verbose_name='Short Description')),
                ('description', models.TextField(verbose_name='Description')),
                ('expire_date', models.DateField(verbose_name='Expiry Date')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock Quantity')),
                ('thumbnail', models.ImageField(default='products/default.jpg', upload_to='products/', verbose_name='Product Thumbnail')),
                ('meta_tags', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meta Tags (SEO)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='medicine_store.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
                'ordering': ['-created_at'],
            },
        ),
    ]
