# Generated by Django 4.2.16 on 2024-11-22 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_store', '0003_medicine_power'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='power',
            field=models.PositiveIntegerField(default=0, verbose_name='Medicine Power(mg)'),
        ),
    ]
