# Generated by Django 4.2.11 on 2024-11-23 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_store', '0004_alter_medicine_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='Slug (for SEO-friendly URL)'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='power',
            field=models.PositiveIntegerField(default=0, verbose_name='Medicine Power (mg)'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated At'),
        ),
    ]
