# Generated by Django 4.2.11 on 2024-12-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_store', '0005_medicine_slug_alter_medicine_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='is_top_selling',
            field=models.BooleanField(default=False, verbose_name='Is Top Selling Product'),
        ),
    ]
