# Generated by Django 4.2.16 on 2024-11-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('logo_url', models.URLField()),
                ('doctor_count', models.IntegerField()),
                ('specialty_count', models.IntegerField()),
                ('fee_range', models.CharField(max_length=100)),
            ],
        ),
    ]
