# Generated by Django 4.2.16 on 2024-11-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('AC', 'AC Ambulance Service'), ('Non AC', 'Non AC Ambulance Service'), ('ALS', 'ALS Ambulance Service'), ('ACLS', 'ACLS Ambulance Service'), ('AIR', 'AIR Ambulance Service'), ('ICU', 'ICU Ambulance Service'), ('NICU', 'NICU Ambulance Service'), ('Freezing', 'Freezing Ambulance Service')], max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('contact_number', models.CharField(max_length=15)),
                ('facilities', models.TextField()),
                ('image_url', models.URLField(default='')),
                ('user_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
            ],
        ),
    ]
