# Generated by Django 4.2.16 on 2024-11-30 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ambulance', '0003_alter_ambulance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='type',
            field=models.CharField(choices=[('AC Ambulance Service', 'AC Ambulance Service'), ('Non AC Ambulance Service', 'Non AC Ambulance Service'), ('ALS Ambulance Service', 'ALS Ambulance Service'), ('ACLS Ambulance Service', 'ACLS Ambulance Service'), ('AIR Ambulance Service', 'AIR Ambulance Service'), ('ICU Ambulance Service', 'ICU Ambulance Service'), ('NICU Ambulance Service', 'NICU Ambulance Service'), ('Freezing Ambulance Service', 'Freezing Ambulance Service')], max_length=26),
        ),
    ]
